set_property IOSTANDARD LVCMOS33 [get_ports {reset}]
set_property PACKAGE_PIN AA19 [get_ports {reset}]

set_property PACKAGE_PIN V13 [get_ports {fnd[7]}]
set_property PACKAGE_PIN V14 [get_ports {fnd[6]}]
set_property PACKAGE_PIN V15 [get_ports {fnd[5]}]
set_property PACKAGE_PIN W15 [get_ports {fnd[4]}]
set_property PACKAGE_PIN W12 [get_ports {fnd[3]}]
set_property PACKAGE_PIN W13 [get_ports {fnd[2]}]
set_property PACKAGE_PIN V11 [get_ports {fnd[1]}]
set_property PACKAGE_PIN W11 [get_ports {fnd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fnd[7]}]

set_property PACKAGE_PIN U11 [get_ports {digit[0]}]
set_property PACKAGE_PIN U12 [get_ports {digit[1]}]
set_property PACKAGE_PIN U13 [get_ports {digit[2]}]
set_property PACKAGE_PIN U14 [get_ports {digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit[0]}]

set_property PACKAGE_PIN U9 [get_ports pcie_ref_clk_p]
set_property PACKAGE_PIN V9 [get_ports pcie_ref_clk_n]
